### ISSUE TITLE
Forms dependency is awkward

### ISSUE THREAD

**Issue by GalaxiaGuy** [exponea/exponea-xamarin-sdk#1]
I'm looking to use Exponea on a Xamarin app that supports iOS and Android that does not depend on Xamarin.Forms, however the nuget package ExponeaSDK has a dependency on Forms.

Ideally that Forms support would be in a separate, optional nuget package for users who are using Forms.

However, it looks like the only thing it is used for is `ExponeaFormsAppDelegate`, and that code might be better served being in some documentation.

Keeping the dependency is also likely to make the transition to .NET 6 and Maui more difficult.

**Comment by xcibik00** [comment]
Hi @GalaxiaGuy ,

We plan and prepare new MAUI SDK (without any Forms dependency) this year, which should solve your issue and make the transition to .NET 6 and Maui easy as possible.

Regards
