### ISSUE TITLE
Tracking stops after Identifying Customer

### ISSUE THREAD

**Issue by JamieHandsMagpie** [exponea/exponea-xamarin-sdk#3]
We're having some issues with this SDK.

Tracking works as expected up until the point that the user logs in and the IdentifyCustomer method is called.

I can see the information is being sent to Exponea, as Exponea is returning success as true and no errors. I am also able to see that the email and customer id are sent in the IdentifyCustomer method, yet when I look on the dashboard, those events are not displayed.

I have also tried searching for the event name rather than the customer id to see if it is somewhere else, but cannot see the events anywhere.

How can we resolve this?

**Comment by adam1929** [comment]
Hi @JamieHandsMagpie
Please look into your logs and try to find any anomalies:
- did your project ID changed?
- are you sure that customer IDs from identifyCustomer are same as while uploading track events?
- are you sending track event data with property that is not allowed to track in you project?
If you see nothing problematic, could you please rise this with support channel? If there is no problem in your project configuration that could ignores your track events.
Thank you

**Comment by JamieHandsMagpie** [comment]
I've checked all of this and everything seems to be sending as expected. We do have a ticket open but need to get this sorted quickly.

**Comment by adam1929** [comment]
Thanks for asking support. I have information that issue has been found with permissions setup on engagement app to track some attributes. (Info for future developers)
